package Modelo;

import java.sql.Date;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Administrador.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public class Administrador extends Empleado {
	
	
	/**
	 * 
	 */
	public Administrador() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param legajo
	 * @param fechaAlta
	 * @param fechaBaja
	 * @param prestamos
	 * @param sanciones
	 * @param devoluciones
	 * @param direccion
	 * @param estado
	 * @param email
	 * @param ciudad
	 * @param telefono
	 * @param dni
	 * @param apellido
	 * @param nombre
	 */
	public Administrador(String legajo, Date fechaAlta, Date fechaBaja,
			ArrayList<Prestamo> prestamos, ArrayList<Sancion> sanciones,
			ArrayList<Devolucion> devoluciones, String direccion,
			String estado, String email, String ciudad, int telefono, int dni,
			String apellido, String nombre) {
		super(legajo, fechaAlta, fechaBaja, prestamos, sanciones, devoluciones,
				direccion, estado, email, ciudad, telefono, dni, apellido, nombre);
		// TODO Auto-generated constructor stub
	}

	@Override
	public ArrayList<Libro> consultarLibro(String titulo, String autor,
			String materia) {
		// TODO Auto-generated method stub
		return super.consultarLibro(titulo, autor, materia);
	}

	@Override
	public void altaSocio(String nombre, String apellido, int dni,
			int telefono, String direccion, String ciudad, String email,
			String estado) {
		// TODO Auto-generated method stub
		super.altaSocio(nombre, apellido, dni, telefono, direccion, ciudad, email,
				estado);
	}

	@Override
	public void altaPrestamo(Socio socio, ArrayList<Libro> Libros,
			Enum tipoPrestamo) {
		// TODO Auto-generated method stub
		super.altaPrestamo(socio, Libros, tipoPrestamo);
	}

	@Override
	public void bajaSocio(Socio socio) {
		// TODO Auto-generated method stub
		super.bajaSocio(socio);
	}

	@Override
	public boolean verificarExistenciaPrestamo(Socio socio) {
		// TODO Auto-generated method stub
		return super.verificarExistenciaPrestamo(socio);
	}

	@Override
	public boolean verificarExistenciaSancion(Socio socio) {
		// TODO Auto-generated method stub
		return super.verificarExistenciaSancion(socio);
	}

	@Override
	public boolean verificarExistenciaSanciones() {
		// TODO Auto-generated method stub
		return super.verificarExistenciaSanciones();
	}

	@Override
	public void modificarSocio(String nombre, String apellido, int dni,
			int telefono, String direccion, String ciudad, String email,
			String estado, Socio socio) {
		// TODO Auto-generated method stub
		super.modificarSocio(nombre, apellido, dni, telefono, direccion, ciudad, email,
				estado, socio);
	}

	@Override
	public void addPrestamo(Prestamo prestamo) {
		// TODO Auto-generated method stub
		super.addPrestamo(prestamo);
	}

	@Override
	public void asentarCumplimientoSancion(Sancion sancion) {
		// TODO Auto-generated method stub
		super.asentarCumplimientoSancion(sancion);
	}

	@Override
	public ArrayList<Prestamo> emitirInformePrestamosVencidos(Date fechaInicio,
			Date fechaFin) {
		// TODO Auto-generated method stub
		return super.emitirInformePrestamosVencidos(fechaInicio, fechaFin);
	}

	@Override
	public ArrayList<Prestamo> emitirInformesLibroSolicitados(Date fechaInicio,
			Date fechaFin) {
		// TODO Auto-generated method stub
		return super.emitirInformesLibroSolicitados(fechaInicio, fechaFin);
	}

	@Override
	public void realizarLogin(String nombreUsuario, String contraseña) {
		// TODO Auto-generated method stub
		super.realizarLogin(nombreUsuario, contraseña);
	}

	@Override
	public void addDevolucion(Devolucion devolucion) {
		// TODO Auto-generated method stub
		super.addDevolucion(devolucion);
	}

	@Override
	public void modificarPrestamo(Prestamo prestamo, ArrayList<Libro> libros,
			Enum tipoPrestamo, Date fechaDevolucion) {
		// TODO Auto-generated method stub
		super.modificarPrestamo(prestamo, libros, tipoPrestamo, fechaDevolucion);
	}

	@Override
	public void addSancion(Sancion sancion) {
		// TODO Auto-generated method stub
		super.addSancion(sancion);
	}

	@Override
	public void altaLibro(String isbn, int autor, String titulo,
			String subtitulo, String editorial, int Edicion, Date añoEdicion,
			double valorMonetario, int volumen, String idioma, int paginas,
			int ejemplares, String tipoAdquisicion, String observacion,
			String estado) {
		// TODO Auto-generated method stub
		super.altaLibro(isbn, autor, titulo, subtitulo, editorial, Edicion, añoEdicion,
				valorMonetario, volumen, idioma, paginas, ejemplares, tipoAdquisicion,
				observacion, estado);
	}

	@Override
	public void bajaLibro(Libro Libro) {
		// TODO Auto-generated method stub
		super.bajaLibro(Libro);
	}

	@Override
	public void bajaPrestamo(Socio socio, ArrayList<Libro> libros,
			Configuracion configuracion) {
		// TODO Auto-generated method stub
		super.bajaPrestamo(socio, libros, configuracion);
	}

	@Override
	public double calcularSancionMonetaria(Prestamo prestamo,
			Devolucion devolucion) {
		// TODO Auto-generated method stub
		return super.calcularSancionMonetaria(prestamo, devolucion);
	}

	@Override
	public ArrayList<Prestamo> informeLibrosPrestados(Date fechaInicio,
			Date fechaFin) {
		// TODO Auto-generated method stub
		return super.informeLibrosPrestados(fechaInicio, fechaFin);
	}

	@Override
	public void ModificarLibro(String isbn, int autor, String titulo,
			String subtitulo, String editorial, int Edicion, Date añoEdicion,
			double valorMonetario, int volumen, String idioma, int paginas,
			int ejemplares, String tipoAdquisicion, String observacion,
			String estado) {
		// TODO Auto-generated method stub
		super.ModificarLibro(isbn, autor, titulo, subtitulo, editorial, Edicion,
				añoEdicion, valorMonetario, volumen, idioma, paginas, ejemplares,
				tipoAdquisicion, observacion, estado);
	}

	@Override
	public boolean verificarPrestamo(Socio socio, ArrayList<Libro> libro) {
		// TODO Auto-generated method stub
		return super.verificarPrestamo(socio, libro);
	}
	@Override
	public int getCantidadPrestamosActivos(Socio socio) {
		// TODO Auto-generated method stub
		return super.getCantidadPrestamosActivos(socio);
	}

	public void modificarAdministrador(String nombre, String Apellido, int dni, int telefono, String direccion, String ciudad, String email, String estado, String contrasenia) {
	
	}
	
	public void modificacionBibliotecario(Bibliotecario bibliotecario, String nombre, String apellido, int dni, String direccion, int telefono, String ciudad, String email, String estado) {
	
	}
	
	
	public void bajaAdministrador(Administrador administrador) {
	
	}
	
	public void bajaBibliotecario(Bibliotecario bibliotecario) {
	
	}
	
	public void altaBibliotecario(String nombre, String apellido, int dni, String direccion, int telefono, String ciudad, String email, String estado) {
	
	}
	
	
	public void altaAdministrador(String nombre, String apellido, int dni, String direccion, int telefono, String ciudad, String email, String estado, String contrasenia) {
	
	}
	
	public void modificarConfiguracion(int cantidadPrestamo, int cantidadReserva, Date tiempoPrestamo, Date tiempoReserva, Date penalizacionRestraso, double coeficienteDestruccion) {
	
	}


/////////////////////////// geters y seters///////////////////////////////////////////////
	@Override
	public String getLegajo() {
		// TODO Auto-generated method stub
		return super.getLegajo();
	}

	@Override
	public void setLegajo(String legajo) {
		// TODO Auto-generated method stub
		super.setLegajo(legajo);
	}

	@Override
	public String getNombre() {
		// TODO Auto-generated method stub
		return super.getNombre();
	}

	@Override
	public void setNombre(String nombre) {
		// TODO Auto-generated method stub
		super.setNombre(nombre);
	}

	@Override
	public String getDireccion() {
		// TODO Auto-generated method stub
		return super.getDireccion();
	}

	@Override
	public void setDireccion(String direccion) {
		// TODO Auto-generated method stub
		super.setDireccion(direccion);
	}

	@Override
	public String getApellido() {
		// TODO Auto-generated method stub
		return super.getApellido();
	}

	@Override
	public void setApellido(String apellido) {
		// TODO Auto-generated method stub
		super.setApellido(apellido);
	}

	@Override
	public int getDni() {
		// TODO Auto-generated method stub
		return super.getDni();
	}

	@Override
	public void setDni(int dni) {
		// TODO Auto-generated method stub
		super.setDni(dni);
	}

	@Override
	public int getTelefono() {
		// TODO Auto-generated method stub
		return super.getTelefono();
	}

	@Override
	public void setTelefono(int telefono) {
		// TODO Auto-generated method stub
		super.setTelefono(telefono);
	}

	@Override
	public String getCiudad() {
		// TODO Auto-generated method stub
		return super.getCiudad();
	}

	@Override
	public void setCiudad(String ciudad) {
		// TODO Auto-generated method stub
		super.setCiudad(ciudad);
	}

	@Override
	public String getEmail() {
		// TODO Auto-generated method stub
		return super.getEmail();
	}

	@Override
	public void setEmail(String email) {
		// TODO Auto-generated method stub
		super.setEmail(email);
	}

	@Override
	public String getEstado() {
		// TODO Auto-generated method stub
		return super.getEstado();
	}

	@Override
	public void setEstado(String estado) {
		// TODO Auto-generated method stub
		super.setEstado(estado);
	}

	@Override
	public Date getFechaAlta() {
		// TODO Auto-generated method stub
		return super.getFechaAlta();
	}

	@Override
	public void setFechaAlta(Date fechaAlta) {
		// TODO Auto-generated method stub
		super.setFechaAlta(fechaAlta);
	}

	@Override
	public Date getFechaBaja() {
		// TODO Auto-generated method stub
		return super.getFechaBaja();
	}

	@Override
	public void setFechaBaja(Date fechaBaja) {
		// TODO Auto-generated method stub
		super.setFechaBaja(fechaBaja);
	}

	@Override
	public ArrayList<Prestamo> getPrestamos() {
		// TODO Auto-generated method stub
		return super.getPrestamos();
	}

	@Override
	public void setPrestamos(ArrayList<Prestamo> prestamos) {
		// TODO Auto-generated method stub
		super.setPrestamos(prestamos);
	}

	@Override
	public ArrayList<Sancion> getSanciones() {
		// TODO Auto-generated method stub
		return super.getSanciones();
	}

	@Override
	public void setSanciones(ArrayList<Sancion> sanciones) {
		// TODO Auto-generated method stub
		super.setSanciones(sanciones);
	}

	@Override
	public ArrayList<Devolucion> getDevoluciones() {
		// TODO Auto-generated method stub
		return super.getDevoluciones();
	}

	@Override
	public void setDevoluciones(ArrayList<Devolucion> devoluciones) {
		// TODO Auto-generated method stub
		super.setDevoluciones(devoluciones);
	}
}
	