package Modelo;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Autor.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public class Autor {
	private ArrayList<Libro> libros;
	private String nombreAutor;
	private String apellidoAutor;
	
	/**
	 * @param libros
	 * @param nombreAutor
	 * @param apellidoAutor
	 */
	public Autor(ArrayList<Libro> libros, String nombreAutor,
			String apellidoAutor) {
		super();
		this.setLibros(libros);
		this.setNombreAutor(nombreAutor);
		this.setApellidoAutor(apellidoAutor);
	}
	////////////////////////////////////geters y seters/////////////////////////////////////////
	

public ArrayList<Libro> getLibros() {
		return libros;
	}
	public void setLibros(ArrayList<Libro> libros) {
		this.libros = libros;
	}
	public String getNombreAutor() {
		return nombreAutor;
	}
	public void setNombreAutor(String nombreAutor) {
		this.nombreAutor = nombreAutor;
	}
	public String getApellidoAutor() {
		return apellidoAutor;
	}
	public void setApellidoAutor(String apellidoAutor) {
		this.apellidoAutor = apellidoAutor;
	}

	
}
