package Modelo;

import java.sql.Date;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Biblioteca.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public class Biblioteca {
	private ArrayList<Usuario> usuarios;
	private Configuracion configuracion;
	private ArrayList<Libro> libros;
	
	
	
	/**
	 * @param usuarios
	 * @param configuracion
	 * @param libros
	 */
	public Biblioteca(ArrayList<Usuario> usuarios, Configuracion configuracion,
			ArrayList<Libro> libros) {
		super();
		this.setUsuarios(usuarios);
		this.setConfiguracion(configuracion);
		this.setLibros(libros);	
	}

	public void enviarSolicitudSocio(String nombre, String Apellido, int dni, int telefono, String direccion, String ciudad, String email) {
	
	}
	
	public void addUsuario(Usuario usuario) {
	
	}
	
	public boolean verificarUsuario(int dni) {
		return false;
	
	}
	
	public boolean verificarLibro(String isbn) {
		return false;
	
	}
	
	public Libro buscarLibro(String isbn) {
		return null;
	
	}
	
	public Usuario buscarUsuario(int dni) {
		return null;
	
	}
	
	public void modificarReserva(ArrayList<Libro> libros, Enum tipoReserva) {
	
	}
	
	public void solicitudRenovacionCarnet(Socio socio) {
	
	}
	
	public ArrayList<Libro> consultarLibro(String titulo, String autor, String materia) {
		return null;
	
	}
	
	public void altaSocio(String nombre, String apellido, int dni, String direccion, int telefono, String ciudad, String email, String estado) {
	
	}
	
	public void cancelarSolicitudSocio(int dni) {
	
	}
	
	public void bajaSocio(Socio socio) {
	
	}
	
	public void modificarPrestamo(Prestamo prestamo, ArrayList<Libro> libros, Enum tipoPrestamo, Date fechaDevolucion) {
	
	}
	
	public void modificarSocio(String nombre, String Apellido, int dni, int telefono, String direccion, String ciudad, String email, String estado, Socio socio) {
	
	}
	
	public void reservarLibro(ArrayList<Libro> libros, Socio socio) {
	
	}
	
	public void altaLibro(String isbn, int autor, String titulo, String subtitulo, String editorial, int Edicion, Date añoEdicion, double valorMonetario, int volumen, String idioma, int paginas, int ejemplares, String tipoAdquisicion, String observacion, String estado) {
	
	}
	
	public void ModificarLibro(String isbn, int autor, String titulo, String subtitulo, String editorial, int Edicion, Date añoEdicion, double valorMonetario, int volumen, String idioma, int paginas, int ejemplares, String tipoAdquisicion, String observacion, String estado) {
	
	}
	
	public void bajaPrestamo(Socio socio, ArrayList<Libro> libros) {
	
	}
	
	public void AddLibro(Libro libro) {
	
	}
	
	public void bajaLibro(Libro Libro) {
	
	}
	
	public void modificarDevolucion(String estado, ArrayList<Libro> libros) {
	
	}
	
	public void AltaPrestamo(ArrayList<Libro> libros, Socio socio, String tipoPrestamo) {
	
	}
	
	public void realizarLogin(String nombreUsuario, String contraseña) {
	
	}
	
	public boolean verificarLogin() {
		return false;
	
	}
	
	public ArrayList<Prestamo> informeLibrosPrestados(Date fechaInicio, Date fechaFin) {
		return null;
	
	}
	
	public ArrayList<Prestamo> emitirInformePrestamosVencidos(Date fechaInicio, Date fechaFin) {
		return null;
	
	}
	
	public void bajaBibliotecario(Bibliotecario bibliotecario) {
	
	}
	
	public void altaBibliotecario(String nombre, String apellido, int dni, String direccion, int telefono, String ciudad, String email, String estado) {
	
	}
	
	public ArrayList<Prestamo> emitirInformesLibroSolicitados(Date fechaInicio, Date fechaFin) {
		return null;
	
	}
	
	public void asentarCumplimientoSancion(Sancion sancion) {
	
	}
	
	public void bajaAdministrador(Administrador administrador) {
	
	}
	
	public void modificacionBibliotecario(Bibliotecario bibliotecario, String nombre, String apellido, int dni, String direccion, int telefono, String ciudad, String email, String estado) {
	
	}
	
	public void modificarConfiguracion(int cantidadPrestamo, int cantidadReserva, Date tiempoPrestamo, Date tiempoReserva, Date penalizacionRestraso, double coeficienteDestruccion) {
	
	}
	
	public void altaAdministrador(String nombre, String apellido, int dni, String direccion, int telefono, String ciudad, String email, String estado, String contrasenia) {
	
	}
	
	public void modificarAdministrador(Administrador administrador, String nombre, String Apellido, int dni, int telefono, String direccion, String ciudad, String email, String estado, String contrasenia) {
	
	}
	////////////////////////////////////geters y seters/////////////////////////////////////////

	public ArrayList<Usuario> getUsuarios() {
		return usuarios;
	}

	public void setUsuarios(ArrayList<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public Configuracion getConfiguracion() {
		return configuracion;
	}

	public void setConfiguracion(Configuracion configuracion) {
		this.configuracion = configuracion;
	}

	public ArrayList<Libro> getLibros() {
		return libros;
	}

	public void setLibros(ArrayList<Libro> libros) {
		this.libros = libros;
	}
	
}
