package Modelo;

import java.sql.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Configuracion.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public class Configuracion {
	private Administrador administrador;
	private Biblioteca biblioteca;
	private int cantidadPrestamos;
	private int cantidadReservas;
	private Date tiempoPrestamo;
	private Date tiempoReserva;
	private int penalizacionRetrazo;
	private double coeficienteDestruccion;
	
	
	/**
	 * @param administrador
	 * @param biblioteca
	 * @param cantidadPrestamos
	 * @param cantidadReservas
	 * @param tiempoPrestamo
	 * @param tiempoReserva
	 * @param penalizacionRetrazo
	 * @param coeficienteDestruccion
	 */
	public Configuracion(Administrador administrador, Biblioteca biblioteca,
			int cantidadPrestamos, int cantidadReservas, Date tiempoPrestamo,
			Date tiempoReserva, int penalizacionRetrazo,
			double coeficienteDestruccion) {
		super();
		this.setAdministrador(administrador);
		this.setBiblioteca(biblioteca);
		this.setCantidadPrestamos(cantidadPrestamos);
		this.setCantidadReservas(cantidadReservas);
		this.setTiempoPrestamo(tiempoPrestamo);
		this.setTiempoReserva(tiempoReserva);
		this.setPenalizacionRetrazo(penalizacionRetrazo);
		this.setCoeficienteDestruccion(coeficienteDestruccion);
	}
	////////////////////////////////////geters y seters/////////////////////////////////////////
	public Administrador getAdministrador() {
		return administrador;
	}
	public void setAdministrador(Administrador administrador) {
		this.administrador = administrador;
	}
	public Biblioteca getBiblioteca() {
		return biblioteca;
	}
	public void setBiblioteca(Biblioteca biblioteca) {
		this.biblioteca = biblioteca;
	}
	public int getCantidadPrestamos() {
		return cantidadPrestamos;
	}
	public void setCantidadPrestamos(int cantidadPrestamos) {
		this.cantidadPrestamos = cantidadPrestamos;
	}
	public int getCantidadReservas() {
		return cantidadReservas;
	}
	public void setCantidadReservas(int cantidadReservas) {
		this.cantidadReservas = cantidadReservas;
	}
	public Date getTiempoPrestamo() {
		return tiempoPrestamo;
	}
	public void setTiempoPrestamo(Date tiempoPrestamo) {
		this.tiempoPrestamo = tiempoPrestamo;
	}
	public Date getTiempoReserva() {
		return tiempoReserva;
	}
	public void setTiempoReserva(Date tiempoReserva) {
		this.tiempoReserva = tiempoReserva;
	}
	public int getPenalizacionRetrazo() {
		return penalizacionRetrazo;
	}
	public void setPenalizacionRetrazo(int penalizacionRetrazo) {
		this.penalizacionRetrazo = penalizacionRetrazo;
	}
	public double getCoeficienteDestruccion() {
		return coeficienteDestruccion;
	}
	public void setCoeficienteDestruccion(double coeficienteDestruccion) {
		this.coeficienteDestruccion = coeficienteDestruccion;
	}
	
}
