package Modelo;

import java.sql.Date;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Devolucion.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public class Devolucion {
	private ArrayList<Libro> libros;
	private Socio socio;
	private Bibliotecario bobliotecario;
	private Date fechaRealDevolucion;
	private String estado;
	
	public Devolucion(ArrayList<Libro> libros, Socio socio,
			Bibliotecario bobliotecario, Date fechaRealDevolucion, String estado) {
		super();
		this.setLibros(libros);
		this.setSocio(socio);
		this.setBobliotecario(bobliotecario);
		this.setFechaRealDevolucion(fechaRealDevolucion) ;
		this.setEstado(estado) ;
	}
	////////////////////////////////////geters y seters/////////////////////////////////////////
	public ArrayList<Libro> getLibros() {
		return libros;
	}
	public void setLibros(ArrayList<Libro> libros) {
		this.libros = libros;
	}
	public Socio getSocio() {
		return socio;
	}
	public void setSocio(Socio socio) {
		this.socio = socio;
	}
	public Bibliotecario getBobliotecario() {
		return bobliotecario;
	}
	public void setBobliotecario(Bibliotecario bobliotecario) {
		this.bobliotecario = bobliotecario;
	}
	public Date getFechaRealDevolucion() {
		return fechaRealDevolucion;
	}
	public void setFechaRealDevolucion(Date fechaRealDevolucion) {
		this.fechaRealDevolucion = fechaRealDevolucion;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	
}
