package Modelo;

import java.sql.Date;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Empleado.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public abstract class Empleado extends Usuario {
	
    protected String legajo;
	protected ArrayList<Prestamo> prestamos;
	protected ArrayList<Sancion> sanciones;
	protected ArrayList<Devolucion> devoluciones;

	
	
	
	/**
	 * @param legajo
	 * @param fechaAlta
	 * @param fechaBaja
	 * @param prestamos
	 * @param sanciones
	 * @param devoluciones
	 * @param direccion
	 * @param estado
	 * @param email
	 * @param ciudad
	 * @param telefono
	 * @param dni
	 * @param apellido
	 * @param nombre
	 */
	public Empleado(String legajo, Date fechaAlta, Date fechaBaja,
			ArrayList<Prestamo> prestamos, ArrayList<Sancion> sanciones,
			ArrayList<Devolucion> devoluciones, String direccion,
			String estado, String email, String ciudad, int telefono, int dni,
			String apellido, String nombre) {
		super(nombre, direccion, apellido, dni, telefono, ciudad, email, estado,
				fechaAlta, fechaBaja);
		this.setLegajo(legajo);
		this.setPrestamos(prestamos);
		this.setSanciones(sanciones);
		this.setDevoluciones(devoluciones);
	}

	/**
	 * 
	 */
	public Empleado() {
		super();
		// TODO Auto-generated constructor stub
	}


	@Override
	public ArrayList<Libro> consultarLibro(String titulo, String autor,
			String materia) {
		// TODO Auto-generated method stub
		return super.consultarLibro(titulo, autor, materia);
	}

	public void altaSocio(String nombre, String apellido, int dni, int telefono, String direccion, String ciudad, String email, String estado) {
	
	}
	
	public void altaPrestamo(Socio socio, ArrayList<Libro> Libros, Enum tipoPrestamo) {
	
	}
	
	public void bajaSocio(Socio socio) {
	
	}
	
	public boolean verificarExistenciaPrestamo(Socio socio) {
		return false;
	
	}
	
	public boolean verificarExistenciaSancion(Socio socio) {
		return false;
	
	}
	
	public boolean verificarExistenciaSanciones() {
		return false;
	
	}
	
	public int getCantidadPrestamosActivos(Socio socio) {
		return dni;
	
	}
	
	public void modificarSocio(String nombre, String apellido, int dni, int telefono, String direccion, String ciudad, String email, String estado, Socio socio) {
	
	}
	
	public void addPrestamo(Prestamo prestamo) {
	
	}
	
	public void asentarCumplimientoSancion(Sancion sancion) {
	
	}
	
	public ArrayList<Prestamo> emitirInformePrestamosVencidos(Date fechaInicio, Date fechaFin) {
		return null;
	
	}
	
	public ArrayList<Prestamo> emitirInformesLibroSolicitados(Date fechaInicio, Date fechaFin) {
		return null;
	
	}
	
	public void realizarLogin(String nombreUsuario, String contraseña) {
	
	}
	
	public void addDevolucion(Devolucion devolucion) {
	
	}
	
	public void modificarPrestamo(Prestamo prestamo, ArrayList<Libro> libros, Enum tipoPrestamo, Date fechaDevolucion) {
	
	}
	
	public void addSancion(Sancion sancion) {
	
	}
	
	public void altaLibro(String isbn, int autor, String titulo, String subtitulo, String editorial, int Edicion, Date añoEdicion, double valorMonetario, int volumen, String idioma, int paginas, int ejemplares, String tipoAdquisicion, String observacion, String estado) {
	
	}
	
	public void bajaLibro(Libro Libro) {
	
	}
	
	public void bajaPrestamo(Socio socio, ArrayList<Libro> libros, Configuracion configuracion) {
	
	}
	
	public double calcularSancionMonetaria(Prestamo prestamo, Devolucion devolucion) {
		return 0.0;
	
	}
	
	public ArrayList<Prestamo> informeLibrosPrestados(Date fechaInicio, Date fechaFin) {
		return null;
	
	}
	
	public void ModificarLibro(String isbn, int autor, String titulo, String subtitulo, String editorial, int Edicion, Date añoEdicion, double valorMonetario, int volumen, String idioma, int paginas, int ejemplares, String tipoAdquisicion, String observacion, String estado) {
	
	}
	
	public boolean verificarPrestamo(Socio socio, ArrayList<Libro> libro) {
		return false;
	
	}
	////////////////////////////////////geters y seters/////////////////////////////////////////

	public String getLegajo() {
		return legajo;
	}

	public void setLegajo(String legajo) {
		this.legajo = legajo;
	}

	@Override
	public String getNombre() {
		// TODO Auto-generated method stub
		return super.getNombre();
	}

	@Override
	public void setNombre(String nombre) {
		// TODO Auto-generated method stub
		super.setNombre(nombre);
	}

	@Override
	public String getDireccion() {
		// TODO Auto-generated method stub
		return super.getDireccion();
	}

	@Override
	public void setDireccion(String direccion) {
		// TODO Auto-generated method stub
		super.setDireccion(direccion);
	}

	@Override
	public String getApellido() {
		// TODO Auto-generated method stub
		return super.getApellido();
	}

	@Override
	public void setApellido(String apellido) {
		// TODO Auto-generated method stub
		super.setApellido(apellido);
	}

	@Override
	public int getDni() {
		// TODO Auto-generated method stub
		return super.getDni();
	}

	@Override
	public void setDni(int dni) {
		// TODO Auto-generated method stub
		super.setDni(dni);
	}

	@Override
	public int getTelefono() {
		// TODO Auto-generated method stub
		return super.getTelefono();
	}

	@Override
	public void setTelefono(int telefono) {
		// TODO Auto-generated method stub
		super.setTelefono(telefono);
	}

	@Override
	public String getCiudad() {
		// TODO Auto-generated method stub
		return super.getCiudad();
	}

	@Override
	public void setCiudad(String ciudad) {
		// TODO Auto-generated method stub
		super.setCiudad(ciudad);
	}

	@Override
	public String getEmail() {
		// TODO Auto-generated method stub
		return super.getEmail();
	}

	@Override
	public void setEmail(String email) {
		// TODO Auto-generated method stub
		super.setEmail(email);
	}

	@Override
	public String getEstado() {
		// TODO Auto-generated method stub
		return super.getEstado();
	}

	@Override
	public void setEstado(String estado) {
		// TODO Auto-generated method stub
		super.setEstado(estado);
	}

	@Override
	public Date getFechaAlta() {
		// TODO Auto-generated method stub
		return super.getFechaAlta();
	}

	@Override
	public void setFechaAlta(Date fechaAlta) {
		// TODO Auto-generated method stub
		super.setFechaAlta(fechaAlta);
	}

	@Override
	public Date getFechaBaja() {
		// TODO Auto-generated method stub
		return super.getFechaBaja();
	}

	@Override
	public void setFechaBaja(Date fechaBaja) {
		// TODO Auto-generated method stub
		super.setFechaBaja(fechaBaja);
	}

	public ArrayList<Prestamo> getPrestamos() {
		return prestamos;
	}

	public void setPrestamos(ArrayList<Prestamo> prestamos) {
		this.prestamos = prestamos;
	}

	public ArrayList<Sancion> getSanciones() {
		return sanciones;
	}

	public void setSanciones(ArrayList<Sancion> sanciones) {
		this.sanciones = sanciones;
	}

	public ArrayList<Devolucion> getDevoluciones() {
		return devoluciones;
	}

	public void setDevoluciones(ArrayList<Devolucion> devoluciones) {
		this.devoluciones = devoluciones;
	}


	
}
