package Modelo;

import java.awt.Image;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Libro.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public class Libro {
	private String isbn;
	private ArrayList<Autor> autores;
	private String titulo;
	private String subtitulo;
	private String editorial;
	private String añoEdicion;
	private double valorMonetario;
	private int volumen;
	private String idioma;
	private int paginas;
	private int ejemplares;
	private String tipoAdquisicion;
	private String observaciones;
	private String estado;
	private int disponibilidadSala;
	private int disponibilidadEntrega;
	private Enum tipoDisponibilidad;
	private Image imagen;
	
	
	/**
	 * @param isbn
	 * @param autores
	 * @param titulo
	 * @param subtitulo
	 * @param editorial
	 * @param añoEdicion
	 * @param valorMonetario
	 * @param volumen
	 * @param idioma
	 * @param paginas
	 * @param ejemplares
	 * @param tipoAdquisicion
	 * @param observaciones
	 * @param estado
	 * @param disponibilidadSala
	 * @param disponibilidadEntrega
	 * @param tipoDisponibilidad
	 */
	public Libro(String isbn, ArrayList<Autor> autores, String titulo,
			String subtitulo, String editorial, String añoEdicion,
			double valorMonetario, int volumen, String idioma, int paginas,
			int ejemplares, String tipoAdquisicion, String observaciones,
			String estado, int disponibilidadSala, int disponibilidadEntrega,
			Enum tipoDisponibilidad, Image imagen) {
		super();
		this.setIsbn(isbn);
		this.setAutores(autores);
		this.setTitulo(subtitulo);
		this.setSubtitulo(subtitulo);
		this.setEditorial(editorial);
		this.setAñoEdicion(añoEdicion);
		this.setValorMonetario(valorMonetario);
		this.setVolumen(volumen);
		this.setIdioma(idioma);
		this.setPaginas(paginas);
		this.setEjemplares(ejemplares);
		this.setTipoAdquisicion(tipoAdquisicion);
		this.setObservaciones(observaciones);
		this.setEstado(estado);
		this.setDisponibilidadEntrega(disponibilidadEntrega);
		this.setDisponibilidadSala(disponibilidadSala);
		this.setTipoDisponibilidad(tipoDisponibilidad);
		this.setImagen(imagen);
	}

	public boolean verificarDisponibilidadLibro(Enum tipoDisponibilidad) {
		return false;
	
	}
	////////////////////////////////////geters y seters/////////////////////////////////////////

	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public ArrayList<Autor> getAutores() {
		return autores;
	}

	public void setAutores(ArrayList<Autor> autores) {
		this.autores = autores;
	}

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getSubtitulo() {
		return subtitulo;
	}

	public void setSubtitulo(String subtitulo) {
		this.subtitulo = subtitulo;
	}

	public String getEditorial() {
		return editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public String getAñoEdicion() {
		return añoEdicion;
	}

	public void setAñoEdicion(String añoEdicion) {
		this.añoEdicion = añoEdicion;
	}

	public double getValorMonetario() {
		return valorMonetario;
	}

	public void setValorMonetario(double valorMonetario) {
		this.valorMonetario = valorMonetario;
	}

	public int getVolumen() {
		return volumen;
	}

	public void setVolumen(int volumen) {
		this.volumen = volumen;
	}

	public String getIdioma() {
		return idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

	public int getPaginas() {
		return paginas;
	}

	public void setPaginas(int paginas) {
		this.paginas = paginas;
	}

	public int getEjemplares() {
		return ejemplares;
	}

	public void setEjemplares(int ejemplares) {
		this.ejemplares = ejemplares;
	}

	public String getTipoAdquisicion() {
		return tipoAdquisicion;
	}

	public void setTipoAdquisicion(String tipoAdquisicion) {
		this.tipoAdquisicion = tipoAdquisicion;
	}

	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public int getDisponibilidadSala() {
		return disponibilidadSala;
	}

	public void setDisponibilidadSala(int disponibilidadSala) {
		this.disponibilidadSala = disponibilidadSala;
	}

	public int getDisponibilidadEntrega() {
		return disponibilidadEntrega;
	}

	public void setDisponibilidadEntrega(int disponibilidadEntrega) {
		this.disponibilidadEntrega = disponibilidadEntrega;
	}

	public Enum getTipoDisponibilidad() {
		return tipoDisponibilidad;
	}

	public void setTipoDisponibilidad(Enum tipoDisponibilidad) {
		this.tipoDisponibilidad = tipoDisponibilidad;
	}

	public Image getImagen() {
		return imagen;
	}

	public void setImagen(Image imagen) {
		this.imagen = imagen;
	}
	
}
