package Modelo;

import java.sql.Date;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SGB
//  @ File Name : Usuario.java
//  @ Date : 23/09/2012
//  @ Author : Grupo 3
//
//




public abstract class Usuario {
	protected String nombre;
	protected String direccion;
	protected String apellido;
	protected int dni;
	protected int telefono;
	protected String ciudad;
	protected String email;
	protected String estado;
	protected Date fechaAlta;
	protected Date FechaBaja;
	
	
	
	/**
	 * @param nombre
	 * @param direccion
	 * @param apellido
	 * @param dni
	 * @param telefono
	 * @param ciudad
	 * @param email
	 * @param estado
	 * @param fechaAlta
	 * @param fechaBaja
	 */
	public Usuario(String nombre, String direccion, String apellido, int dni,
			int telefono, String ciudad, String email, String estado,
			Date fechaAlta, Date fechaBaja) {
		super();
		this.setNombre(nombre);
		this.setDireccion(direccion);
		this.setApellido(apellido);
		this.setDni(dni);
		this.setTelefono(telefono);
		this.setCiudad(ciudad);
		this.setEmail(email);
		this.setEstado(estado);
		this.setFechaAlta(fechaAlta);
		this.setFechaBaja(fechaBaja);
	}
	/**
	 * 
	 */
	public Usuario() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	public ArrayList<Libro> consultarLibro(String titulo, String autor, String materia){
	return null;
	}
	////////////////////////////////////geters y seters/////////////////////////////////////////
	
	

	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getDireccion() {
		return direccion;
	}
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	public String getApellido() {
		return apellido;
	}
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}
	public int getDni() {
		return dni;
	}
	public void setDni(int dni) {
		this.dni = dni;
	}
	public int getTelefono() {
		return telefono;
	}
	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}
	public String getCiudad() {
		return ciudad;
	}
	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	public Date getFechaAlta() {
		return fechaAlta;
	}
	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	public Date getFechaBaja() {
		return FechaBaja;
	}
	public void setFechaBaja(Date fechaBaja) {
		FechaBaja = fechaBaja;
	}
	

}
